### PR TITLE
implement support for memory_profiler

### LINKED ISSUE #18: Add memory profiler ?
It is based on line_profiler, works with the same decorator ```@profile``` and has the same kind of output : https://github.com/fabianp/memory_profiler

### PR DESCRIPTION
**Pull request by cmeeren**
Closes #18.

Tested on Windows 7 (two PCs) and Ubuntu 14.10.

Readme updated. The two new files `p_memoryprofiler.py` and `widgets/memoryprofilergui.py` are almost identical to the line_profiler versions (occurrences of "line" have more or less been replaced with "memory"). The most significant changes are:

* Code added in `MemoryProfilerDataTree.load_data()` to get the memory_profiler output (already human-readable) into a form readable by the rest of the code.
* Code changed to reflect different number of columns and content
* Call signature changed from `kernprof` to `python -m memory_profiler`

You're welcome. :)

### CODE REVIEW

**Comment by cmeeren** [comment]
@Nodd, did you see this?

**Comment by Nodd** [comment]
Yes, sorry, I forgot about it... I tested it briefly and it seemed to work fine.

Looking at the code, I'm not sure I like the intermediate ```Lstats``` class. This means that you're parsing the data twice. I understand your idea of reusing code as much as possible, but:
* it's in a new module anyway so the reused code is actually a copy-paste and not the same code, reusing it lost most of it's value
* the ```load_data``` method has now more than 100 lines of code and many levels of complexity.

Could you try to transforming the structure given by memory_profiler into the ```self.stats``` dictionary without the intermediate step ?

**Comment by cmeeren** [comment]
Hi again. I have let your reply stay in my inbox for a while with the hope that I'll have the time to have a look at it, but I don't. I fully understand your reluctancy to merge this as it is now, but I re-used the code not for efficiency, but because I have no knowledge of spyder plugins.

It works and that's what matters most to me and, I should think, all users. I would of course also like to see it implemented more "gracefully", but I simply cannot justify the time it would take when I have something that works and way too much other stuff going on.

I hope you understand.

**Comment by Nodd** [comment]
I fully understand, lack of time is the reason why I didn't implement it myself in the first place.

I'll merge this and open an issue to simplify it. I'll do it someday... later...

**Pull request merged**
